### ISSUE TITLE
Flat printing is incorrect for some terms

### ISSUE THREAD

**Issue by kquick** [aisamanra/s-cargot#10]
See commit https://github.com/aisamanra/s-cargot/pull/9/commits/ac643f289b0de8be961b3b1d46592fe2e497b419 for enhanced testing that reveals this issue.  

For certain SExpr representations (see the test), the printer can emit output like:
     `((one . two) three . four)` or `(one two three . four)`

These should probably be, respectively:
     `((one . two) (three . four))` and `(one two (three . four))`

**Comment by kquick** [comment]
Fixed in https://github.com/aisamanra/s-cargot/pull/9/commits/9e2ae3aded81ae133bf18f583a94419ec03c75eb

**Comment by kquick** [comment]
Fix moved to https://github.com/aisamanra/s-cargot/pull/11

**Comment by aisamanra** [comment]
I mentioned this in the closed PR, but for posterity's sake on this issue: this is working as intended, and the fix isn't semantically identical to the original.

Here's an example of a Scheme (well, Guile) REPL session where Guile's pretty-printer produces the same output as `s-cargot`:

```
scheme@(guile-user)> (cons (cons 'one 'two) (cons 'three 'four))
$1 = ((one . two) three . four)
scheme@(guile-user)> (cons 'one (cons 'two (cons 'three 'four)))
$2 = (one two three . four)
```
